### ISSUE TITLE
TypeError: _output_padding() missing 1 required positional argument: 'num_spatial_dims'

### ISSUE THREAD

**Issue by dianxin556** [mit-han-lab/gan-compression#110] opened 2022-11-28 08:19 UTC
when I run the script train_supernet.sh in the fast gan compression,it occurs an error " TypeError: _output_padding() missing 1 required positional argument: 'num_spatial_dims'".
![image](https://user-images.githubusercontent.com/6285399/204227864-59e42d1b-cc13-4d8e-9ab0-ac72afd2dd14.png)
and the task script is "bash scripts/cycle_gan/horse2zebra_fast/train_supernet.sh"

**Comment by lmxyy** [comment] 2022-11-28 17:26
Hi, this issue seems to be caused by the inconsistent PyTorch version. Our code is tested on PyTorch 1.4. Could you specify your PyTorch version?

**Comment by lmxyy** [comment] 2022-11-28 17:31
From the latest PyTorch1.13 document, this can by fixed by changing [this line](https://github.com/mit-han-lab/gan-compression/blob/3dd79dd4973e4bdad511169fde89b3e9e12adc5e/models/modules/super_modules.py#L36) to
```python
num_spatial_dims = 2
output_padding = self._output_padding(x, output_size, self.stride, self.padding, self.kernel_size, num_spatial_dims, self.dilation)
```

**Comment by lmxyy** [comment] 2022-12-06 00:34
As there are no more replies, I will close this issue.

**Closed** 2022-12-06 00:33 UTC

**Comment by dianxin556** [comment] 2022-12-07 03:51
Thanks，I will try.
